[alembic]
# Path to migration scripts
script_location = alembic
prepend_sys_path = .
path_separator = os

# Database URL — leave empty if you want to load from .env in env.py
#production
sqlalchemy.url = postgresql://neondb_owner:npg_NRKpHdGe4Ct5@ep-frosty-band-ahba88lk-pooler.c-3.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require

# sqlalchemy.url = postgresql://postgres:madhu123@localhost:5432/Fliplyn 
# sqlalchemy.url=postgresql://neondb_owner:npg_ujRa8P0wAIXc@ep-plain-term-adq5b7v2-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require


[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
