"""added lawyer

Revision ID: 11a2ee26dc5a
Revises: d63655fe7580
Create Date: 2025-12-11 17:10:19.838468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a2ee26dc5a'
down_revision: Union[str, Sequence[str], None] = 'd63655fe7580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lawyers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lawyer_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('address_line_1', sa.String(), nullable=False),
    sa.Column('address_line_2', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('website_link', sa.String(), nullable=True),
    sa.Column('linkedin_link', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('known_languages', sa.JSON(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lawyer_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_lawyers_email'), 'lawyers', ['email'], unique=True)
    op.create_index(op.f('ix_lawyers_id'), 'lawyers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lawyers_id'), table_name='lawyers')
    op.drop_index(op.f('ix_lawyers_email'), table_name='lawyers')
    op.drop_table('lawyers')
    # ### end Alembic commands ###
