"""added password

Revision ID: 36fc52043dc3
Revises: 69ec8b2109da
Create Date: 2025-12-12 11:29:44.477092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36fc52043dc3'
down_revision: Union[str, Sequence[str], None] = '69ec8b2109da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lawyers', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lawyers', 'password')
    # ### end Alembic commands ###
