"""added lawyer

Revision ID: 69ec8b2109da
Revises: 11a2ee26dc5a
Create Date: 2025-12-11 17:27:53.605510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69ec8b2109da'
down_revision: Union[str, Sequence[str], None] = '11a2ee26dc5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lawyers', sa.Column('rejected_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lawyers', 'rejected_reason')
    # ### end Alembic commands ###
