"""added admin

Revision ID: 72b23499dc2c
Revises: 87f1e52eff4b
Create Date: 2025-12-11 16:22:10.753541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b23499dc2c'
down_revision: Union[str, Sequence[str], None] = '87f1e52eff4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('hashed_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'hashed_password')
    # ### end Alembic commands ###
