"""add column for expirence

Revision ID: 8dae3847d063
Revises: e4b8975b06d8
Create Date: 2026-02-07 15:29:53.611296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dae3847d063'
down_revision: Union[str, Sequence[str], None] = 'e4b8975b06d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lawyers', sa.Column('experience', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lawyers', 'experience')
    # ### end Alembic commands ###
