"""update_lawyer_model

Revision ID: 9569247a64c1
Revises: 6e5c7fdbf11a
Create Date: 2026-05-01 15:52:37.636914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9569247a64c1'
down_revision: Union[str, Sequence[str], None] = '6e5c7fdbf11a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lawyers', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('lawyers', sa.Column('practice_areas', sa.JSON(), nullable=True))
    op.add_column('lawyers', sa.Column('courts', sa.JSON(), nullable=True))
    op.drop_column('lawyers', 'experience')
    op.drop_column('lawyers', 'position_status_days')
    op.drop_column('lawyers', 'position_status_expiry')
    op.drop_column('lawyers', 'address_line_2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lawyers', sa.Column('address_line_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('lawyers', sa.Column('position_status_expiry', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('lawyers', sa.Column('position_status_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lawyers', sa.Column('experience', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('lawyers', 'courts')
    op.drop_column('lawyers', 'practice_areas')
    op.drop_column('lawyers', 'bio')
    # ### end Alembic commands ###
