"""add position_status to lawyers

Revision ID: e4b8975b06d8
Revises: 6e5c7fdbf11a
Create Date: 2026-01-30 18:00:44.858704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4b8975b06d8'
down_revision: Union[str, Sequence[str], None] = '6e5c7fdbf11a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # 1️⃣ Add column as NULLABLE first
    op.add_column(
        'lawyers',
        sa.Column('position_status', sa.String(), nullable=True)
    )

    op.add_column(
        'lawyers',
        sa.Column('position_status_days', sa.Integer(), nullable=True)
    )

    op.add_column(
        'lawyers',
        sa.Column('position_status_expiry', sa.TIMESTAMP(timezone=True), nullable=True)
    )

    # 2️⃣ Backfill existing rows
    op.execute(
        "UPDATE lawyers SET position_status = 'non' WHERE position_status IS NULL"
    )

    # 3️⃣ Enforce NOT NULL constraint
    op.alter_column(
        'lawyers',
        'position_status',
        nullable=False
    )
 # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lawyers', 'position_status_expiry')
    op.drop_column('lawyers', 'position_status_days')
    op.drop_column('lawyers', 'position_status')
    # ### end Alembic commands ###
